import pandas as pd
import plotly.express as px
from flask_app.controllers import admin

# import plotly.offline as pyo


data = {
    "Candidate": [
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Donald John Trump",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
        "Joe Biden",
    ],
   "NumberofVoters": [
    45,
    62,
    50,
    77,
    19,
    53,
    80,
    35,
    91,
    67,
    96,
    59,
    72,
    83,
    42,
    97,
    39,
    55,
    46,
    71,
    33,
    24,
    81,
    78,
    51,
    36,
    65,
    60,
    27,
    84,
    29,
    75,
    56,
    68,
    100,
    87,
    66,
    37,
    89,
    40,
    98,
    61,
    22,
    63,
    74,
    86,
    94,
    23,
    73,
    34,
    48,
    82,
    88,
    69,
    85,
    43,
    21,
    79,
    32,
    90,
    28,
    99,
    64,
    25,
    70,
    31,
    49,
    30,
    92,
    54,
    38,
    57,
    52,
    76,
    41,
    93,
    95,
    26,
    44,
    58,
    105,
    110,
    125,
    211,
    310,
    403,
    504,
    607,
    195,
    111,
    123,
    234,
    345,
    456,
    567,
    678,
    789,
    890,
    901,
    102,
    301
]

,  # Numeric values without '%' symbol
    "region": [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
        "Connecticut"
    ],
}


# Convert to DataFrame
df = pd.DataFrame(data)
# Create the bar chart
fig = px.bar(df, x="Candidate", y="NumberofVoters", color="region", barmode="group")
# Save the figure as an HTML file
html_file_path = "plotly.html"
fig.write_html(html_file_path)
